# Generated by Django 5.0.6 on 2024-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sitesettings_display_sale_text_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(default='usd', max_length=5),
        ),
    ]
