# Generated by Django 5.0.6 on 2024-09-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sitesettings_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
