# Generated by Django 5.0.6 on 2024-09-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_sitesettings_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_collection',
            field=models.CharField(default='Featured', help_text='collection title in medusa', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='number_of_featured_product',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(default='usd', help_text='need to match currecy_code found in query result of product->variant->prices', max_length=5),
        ),
    ]
