# Generated by Django 5.0.6 on 2024-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sitesettings_featured_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='display_contact_info',
            field=models.BooleanField(default=True),
        ),
    ]
