# Generated by Django 5.0.6 on 2024-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sitesettings_display_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='left_collection_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='left_collection_sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='left_collection_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='right_collection_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='right_collection_sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='right_collection_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
