# Generated by Django 5.0.6 on 2024-09-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_sitesettings_left_collection_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='featured_collection',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='number_of_featured_product',
        ),
    ]
