# Generated by Django 5.0.6 on 2024-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_sitesettings_featured_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='left_collection_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='right_collection_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
