# Generated by Django 5.0.6 on 2024-09-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_sitesettings_left_collection_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
