# Generated by Django 5.0.6 on 2024-09-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_progam_overview_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.page'),
        ),
    ]
