# Generated by Django 5.0.6 on 2024-09-25 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_sitesettings_loyalty_progam_overview_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('custom_url', models.CharField(blank=True, help_text='optional if you set a page', max_length=200, null=True)),
                ('display_order', models.IntegerField(default=999)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.page')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
