# Generated by Django 5.0.6 on 2024-09-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_footernav'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
