# Generated by Django 5.0.6 on 2024-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_page_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='active',
        ),
        migrations.AddField(
            model_name='footernav',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
