# Generated by Django 5.0.6 on 2024-09-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_page_active_footernav_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footernav',
            name='active',
        ),
    ]
